//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Semestralka.DatabaseModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Recipes = new HashSet<Recipe>();
        }
    
        public short id_category { get; set; }
        public string name_category { get; set; }
    
        public virtual ICollection<Recipe> Recipes { get; set; }
    }
}
