//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Semestralka.DatabaseModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingredient
    {
        public Ingredient()
        {
            this.Relationship_2 = new HashSet<Recipe_Ingredient>();
        }
    
        public short id_ingredient { get; set; }
        public string name_ingredient { get; set; }
        public string unit { get; set; }
    
        public virtual ICollection<Recipe_Ingredient> Relationship_2 { get; set; }
    }
}
