//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Semestralka.DatabaseModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Ingredient> Ingredients { get; set; }
        public virtual DbSet<Recipe> Recipes { get; set; }
        public virtual DbSet<Recipe_Ingredient> Recipe_Ingredient { get; set; }
    
        public virtual int Insert_User(string username, string password, string firstname, string lastname, Nullable<bool> user_right)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var firstnameParameter = firstname != null ?
                new ObjectParameter("firstname", firstname) :
                new ObjectParameter("firstname", typeof(string));
    
            var lastnameParameter = lastname != null ?
                new ObjectParameter("lastname", lastname) :
                new ObjectParameter("lastname", typeof(string));
    
            var user_rightParameter = user_right.HasValue ?
                new ObjectParameter("user_right", user_right) :
                new ObjectParameter("user_right", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_User", usernameParameter, passwordParameter, firstnameParameter, lastnameParameter, user_rightParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Insert_Category(string name_category)
        {
            var name_categoryParameter = name_category != null ?
                new ObjectParameter("name_category", name_category) :
                new ObjectParameter("name_category", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Insert_Category", name_categoryParameter);
        }
    
        public virtual int category_Delete(string name_category)
        {
            var name_categoryParameter = name_category != null ?
                new ObjectParameter("name_category", name_category) :
                new ObjectParameter("name_category", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("category_Delete", name_categoryParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Insert_Recipe(string name_recipe, Nullable<short> id_category, string instructions)
        {
            var name_recipeParameter = name_recipe != null ?
                new ObjectParameter("name_recipe", name_recipe) :
                new ObjectParameter("name_recipe", typeof(string));
    
            var id_categoryParameter = id_category.HasValue ?
                new ObjectParameter("id_category", id_category) :
                new ObjectParameter("id_category", typeof(short));
    
            var instructionsParameter = instructions != null ?
                new ObjectParameter("instructions", instructions) :
                new ObjectParameter("instructions", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Insert_Recipe", name_recipeParameter, id_categoryParameter, instructionsParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Insert_Ingredient(string name_ingredient, string unit)
        {
            var name_ingredientParameter = name_ingredient != null ?
                new ObjectParameter("name_ingredient", name_ingredient) :
                new ObjectParameter("name_ingredient", typeof(string));
    
            var unitParameter = unit != null ?
                new ObjectParameter("unit", unit) :
                new ObjectParameter("unit", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Insert_Ingredient", name_ingredientParameter, unitParameter);
        }
    
        public virtual int Insert_Recipe_Ingredient(Nullable<int> amount)
        {
            var amountParameter = amount.HasValue ?
                new ObjectParameter("amount", amount) :
                new ObjectParameter("amount", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_Recipe_Ingredient", amountParameter);
        }
    
        public virtual int Insert_Recipe_Ingredient1(Nullable<short> id_recipe, Nullable<short> id_ingredient, Nullable<int> amount)
        {
            var id_recipeParameter = id_recipe.HasValue ?
                new ObjectParameter("id_recipe", id_recipe) :
                new ObjectParameter("id_recipe", typeof(short));
    
            var id_ingredientParameter = id_ingredient.HasValue ?
                new ObjectParameter("id_ingredient", id_ingredient) :
                new ObjectParameter("id_ingredient", typeof(short));
    
            var amountParameter = amount.HasValue ?
                new ObjectParameter("amount", amount) :
                new ObjectParameter("amount", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_Recipe_Ingredient1", id_recipeParameter, id_ingredientParameter, amountParameter);
        }
    
        public virtual int Insert_Recipe_Ingredient2(Nullable<short> id_recipe, Nullable<short> id_ingredient, Nullable<int> amount)
        {
            var id_recipeParameter = id_recipe.HasValue ?
                new ObjectParameter("id_recipe", id_recipe) :
                new ObjectParameter("id_recipe", typeof(short));
    
            var id_ingredientParameter = id_ingredient.HasValue ?
                new ObjectParameter("id_ingredient", id_ingredient) :
                new ObjectParameter("id_ingredient", typeof(short));
    
            var amountParameter = amount.HasValue ?
                new ObjectParameter("amount", amount) :
                new ObjectParameter("amount", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_Recipe_Ingredient2", id_recipeParameter, id_ingredientParameter, amountParameter);
        }
    }
}
