//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Semestralka.DatabaseModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe
    {
        public Recipe()
        {
            this.Recipe_Step = new HashSet<Recipe_Step>();
        }
    
        public short id_recipe { get; set; }
        public short id_category { get; set; }
        public string name_recipe { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<Recipe_Step> Recipe_Step { get; set; }
    }
}
