//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Semestralka.DatabaseModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe_Step
    {
        public Recipe_Step()
        {
            this.Recipe_Step_Ingredients = new HashSet<Recipe_Step_Ingredients>();
        }
    
        public short step_number { get; set; }
        public short id_recipe { get; set; }
        public string instruction { get; set; }
    
        public virtual Recipe Recipe { get; set; }
        public virtual ICollection<Recipe_Step_Ingredients> Recipe_Step_Ingredients { get; set; }
    }
}
